export const GET_PEOPLE_INIT = 'GET_PEOPLE_INIT'
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS'
export const GET_PEOPLE_FAILURE = 'GET_PEOPLE_FAILURE'

export const GET_PLANET_INIT = 'GET_PLANET_INIT'
export const GET_PLANET_SUCCESS = 'GET_PLANET_SUCCESS'
export const GET_PLANET_FAILURE = 'GET_PLANET_FAILURE'
